### ISSUE TITLE
Wrong link for scan library in README.md

### ISSUE THREAD

**Issue by ByeongsuPark** [prateekcode/AndroidEssentialLibraries#9]
Hi, @prateekcode thanks for a great project.
I found a link which guess as a mistake on ```README.md```.
current link for [scan library](https://github.com/prateekcode/AndroidEssentialLibraries#android-scanner) is  ```android-spinkit```.
Is [AndroidScannerDemo](https://github.com/jhansireddy/AndroidScannerDemo) what you are intended to link for?

**Comment by prateekcode** [comment]
Hey, @ByeongsuPark thanks for finding out the issue. I have modified the actual link.
